server:
  port: ${port:8080}

spring:
  profiles:
    include: secret
    active: ${profile}
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR