server:
  port: ${port:8080}

spring:
  profiles:
    include: secret
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR