name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUCKET_NAME: mytamin-deploy
  ZIP_FILE_NAME: mytamin
  APP_NAME: mytamin-app
  DEPLOY_GROUP: deploy-group

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test -x asciidoctor

#     추가 배포 환경 구성을 위해 CI까지만

#      - name: Make Directory
#        run: mkdir -p deploy
#
#      - name: Copy Jar
#        run: cp ./build/libs/*.jar ./deploy
#
#      - name: Copy appspec.yml
#        run: cp appspec.yml ./deploy
#
#      - name: Copy script
#        run: cp ./scripts/*.sh ./deploy
#
#      - name: Make zip file
#        run: zip -r ./$ZIP_FILE_NAME.zip ./deploy
#        shell: bash
#
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ap-northeast-2
#
#      - name: Upload to S3
#        run: aws s3 cp --region ap-northeast-2 ./$ZIP_FILE_NAME.zip s3://$BUCKET_NAME/
#
#      - name: CodeDeploy
#        run: aws deploy create-deployment --application-name $APP_NAME --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name $DEPLOY_GROUP --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$ZIP_FILE_NAME.zip